# Install to an instance running Ubuntu 13.10
- include: rax-servers.yml
  vars:
    image: "ubuntu-1310-saucy-salamander"

- name: Install pycurl
  hosts: docker
  gather_facts: no
  tasks:
    - name: Install pycurl
      apt: pkg=python-pycurl update_cache=yes cache_valid_time=600

- name: Install Docker on Rax Server
  hosts: docker
  roles:
    - angstwad.docker_ubuntu

- include: rax-servers-info.yml
