# Install to an instance running Ubuntu 13.10
- include: rax-servers.yml
  vars:
    image: "ubuntu-1310-saucy-salamander"

- name: Install pycurl
  hosts: docker
  gather_facts: no
  tasks:
    - name: Install pycurl
      apt: pkg=python-pycurl update_cache=yes cache_valid_time=600

- name: Install Docker on Rax Server
  hosts: docker
  roles:
    - angstwad.docker_ubuntu

- name: Server info
  hosts: local
  gather_facts: no
  tasks:
    - name: IP address for server
      debug: 
        msg: "Your server has IP address: {{ hostvars[server_name]['ansible_ssh_host'] }}"

    - name: Login information for server
      debug: 
        msg: "Admin password: {{ hostvars[server_name]['ansible_ssh_pass'] }}"
