# Install to an instance running Ubuntu 12.04
- include: rax-servers.yml
  vars:
    image: "ubuntu-1204-lts-precise-pangolin"

- name: Install pycurl
  hosts: docker
  gather_facts: no
  tasks:
    - name: Install pycurl
      apt: pkg=python-pycurl update_cache=yes cache_valid_time=600

- name: Install Docker on Rax Server
  hosts: docker
  roles:
    - angstwad.docker_ubuntu_1204

- include: rax-servers-info.yml
